ifeq ($(subdir),posix)
sysdep_routines := $(sysdep_routines) getsysinfo
endif

ifeq ($(subdir),misc)
headers := $(headers) utmp.h net/if.h net/if_arp.h net/route.h ufs/fs.h \
	   sys/devio.h sys/dkio.h sys/sysinfo.h elcsd.h
endif
